/**
 * MyProjectTrace Seed Data & Demo Scenarios
 * 
 * 5 Realistic Projects representing remodeling & specialty trades:
 * 1. Smith Kitchen (Active, large remodel, thin cash cushion)
 * 2. Highland Bath Remodel (Active, tile & plumbing, healthy profit position)
 * 3. Oakridge Custom Deck (Active, negative cash position alert demo)
 * 4. Metro Commercial HVAC (Active, high AR alert demo)
 * 5. Sunset Specialty Painting (Active, low margin alert demo)
 */

import { Company, User, Project, Provider, Purchase, ReceiptPage, PurchaseItem, Payment, FinancialAlert, ProjectPhoto, ProjectNote, Client, ProjectDocument } from '../types';

export const DEMO_COMPANY: Company = {
  companyId: 'company_apex_builders',
  companyName: 'Apex Remodeling & Trades LLC',
  ownerUid: 'usr_mike_lead',
  tradeType: 'REMODELER',
  settings: {
    minimumGrossMarginThreshold: 0.25, // 25%
    largePurchaseThreshold: 1500,
    currency: 'USD',
    arWarningThreshold: 15000,
  },
  createdAt: '2026-01-15T08:00:00.000Z',
};

export const DEMO_USERS: User[] = [
  {
    userId: 'usr_mike_lead',
    companyId: 'company_apex_builders',
    name: 'Mike Rodriguez',
    email: 'mike@apexremodel.com',
    role: 'OWNER',
    phone: '(555) 234-5678',
    createdAt: '2026-01-15T08:00:00.000Z',
  },
  {
    userId: 'usr_sarah_admin',
    companyId: 'company_apex_builders',
    name: 'Sarah Chen',
    email: 'sarah@apexremodel.com',
    role: 'ADMIN',
    phone: '(555) 345-6789',
    createdAt: '2026-01-16T09:00:00.000Z',
  },
  {
    userId: 'usr_alex_pm',
    companyId: 'company_apex_builders',
    name: 'Alex Rivera',
    email: 'alex@apexremodel.com',
    role: 'PROJECT_MANAGER',
    phone: '(555) 345-8901',
    createdAt: '2026-01-20T08:30:00.000Z',
  },
  {
    userId: 'usr_dave_field',
    companyId: 'company_apex_builders',
    name: 'Dave Miller',
    email: 'dave@apexremodel.com',
    role: 'FIELD_USER',
    phone: '(555) 456-7890',
    createdAt: '2026-02-01T07:30:00.000Z',
  },
  {
    userId: 'usr_emma_acct',
    companyId: 'company_apex_builders',
    name: 'Emma Watson',
    email: 'emma@apexremodel.com',
    role: 'ACCOUNTING',
    phone: '(555) 567-8901',
    createdAt: '2026-02-10T09:00:00.000Z',
  },
];

export const DEMO_CLIENTS: Client[] = [
  {
    clientId: 'client_smith',
    companyId: 'company_apex_builders',
    clientName: 'Robert & Emily Smith',
    address: '742 Evergreen Terrace, Springfield, OR',
    phone: '(555) 123-4567',
    email: 'robert.smith@example.com',
    notes: 'Homeowner, primary residence renovation.',
    createdAt: '2026-05-15T09:00:00.000Z',
  },
  {
    clientId: 'client_highland',
    companyId: 'company_apex_builders',
    clientName: 'David Highland',
    address: '1420 Highland Ave, Lakeview, OR',
    phone: '(555) 234-8901',
    email: 'd.highland@example.com',
    notes: 'Repeat client, requested high-end finishes.',
    createdAt: '2026-05-25T10:00:00.000Z',
  },
  {
    clientId: 'client_oakridge',
    companyId: 'company_apex_builders',
    clientName: 'Karen Vance',
    address: '88 Oakridge Ridge Rd, Pine Valley, OR',
    phone: '(555) 345-9012',
    email: 'kvance@example.com',
    notes: 'Custom outdoor living build.',
    createdAt: '2026-06-20T11:00:00.000Z',
  },
  {
    clientId: 'client_metro',
    companyId: 'company_apex_builders',
    clientName: 'Metro Properties Inc.',
    address: '400 Industrial Parkway, Suite 200, Eugene, OR',
    phone: '(555) 456-0123',
    email: 'accounts@metroprop.com',
    notes: 'Commercial property management group.',
    createdAt: '2026-04-28T08:00:00.000Z',
  },
  {
    clientId: 'client_sunset',
    companyId: 'company_apex_builders',
    clientName: 'Marcus Wright',
    address: '310 Sunset Hills Court, Oak Hills, OR',
    phone: '(555) 567-1234',
    email: 'mwright@example.com',
    notes: 'Exterior refresh client.',
    createdAt: '2026-07-01T10:00:00.000Z',
  },
];

export const DEMO_PROJECT_DOCUMENTS: ProjectDocument[] = [
  {
    documentId: 'doc_smith_contract',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    documentType: 'CONTRACT',
    fileName: 'Smith_Gourmet_Kitchen_Signed_Agreement.pdf',
    fileSize: 2450000,
    mimeType: 'application/pdf',
    secureStorageReference: 'companies/company_apex_builders/projects/proj_smith_kitchen/documents/doc_smith_contract_Smith_Gourmet_Kitchen_Signed_Agreement.pdf',
    fileUrl: 'https://storage.googleapis.com/demo/smith_contract.pdf',
    uploadedBy: 'Mike Rodriguez',
    createdAt: '2026-05-20T10:30:00.000Z',
  },
  {
    documentId: 'doc_smith_permit',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    documentType: 'PERMIT',
    fileName: 'Springfield_Building_Permit_2026_0942.pdf',
    fileSize: 890000,
    mimeType: 'application/pdf',
    secureStorageReference: 'companies/company_apex_builders/projects/proj_smith_kitchen/documents/doc_smith_permit_Springfield_Building_Permit_2026_0942.pdf',
    fileUrl: 'https://storage.googleapis.com/demo/smith_permit.pdf',
    uploadedBy: 'Sarah Chen',
    createdAt: '2026-05-28T14:15:00.000Z',
  },
];

export const DEMO_PROVIDERS: Provider[] = [
  {
    providerId: 'prov_home_depot',
    companyId: 'company_apex_builders',
    providerName: 'Home Depot',
    normalizedName: 'home depot',
    category: 'Lumber & Building Materials',
    createdAt: '2026-01-20T10:00:00.000Z',
  },
  {
    providerId: 'prov_lowes',
    companyId: 'company_apex_builders',
    providerName: "Lowe's",
    normalizedName: 'lowes',
    category: 'Hardware & Fixtures',
    createdAt: '2026-01-20T10:00:00.000Z',
  },
  {
    providerId: 'prov_floor_decor',
    companyId: 'company_apex_builders',
    providerName: 'Floor & Decor',
    normalizedName: 'floor and decor',
    category: 'Tile & Stone',
    createdAt: '2026-01-20T10:00:00.000Z',
  },
  {
    providerId: 'prov_ferguson',
    companyId: 'company_apex_builders',
    providerName: 'Ferguson Bath & Kitchen',
    normalizedName: 'ferguson',
    category: 'Plumbing & Luxury Fixtures',
    createdAt: '2026-01-20T10:00:00.000Z',
  },
  {
    providerId: 'prov_sherwin_williams',
    companyId: 'company_apex_builders',
    providerName: 'Sherwin-Williams',
    normalizedName: 'sherwin williams',
    category: 'Paint & Coatings',
    createdAt: '2026-01-20T10:00:00.000Z',
  },
];

export const DEMO_PROJECTS: Project[] = [
  {
    projectId: 'proj_smith_kitchen',
    companyId: 'company_apex_builders',
    projectName: 'Smith Kitchen Remodel',
    clientId: 'client_smith',
    clientName: 'Robert & Emily Smith',
    projectAddress: '742 Evergreen Terrace, Springfield, OR',
    contractValue: 35000,
    approvedChangeOrders: 3500,
    startDate: '2026-06-01',
    status: 'ACTIVE',
    notes: 'Full gourmet kitchen gut, custom island, quartz countertops, Marazzi tile floor.',
    createdAt: '2026-05-20T10:00:00.000Z',
  },
  {
    projectId: 'proj_highland_bath',
    companyId: 'company_apex_builders',
    projectName: 'Highland Master Bath',
    clientId: 'client_highland',
    clientName: 'David Highland',
    projectAddress: '1420 Highland Ave, Lakeview, OR',
    contractValue: 24500,
    approvedChangeOrders: 1200,
    startDate: '2026-06-15',
    status: 'ACTIVE',
    notes: 'Walk-in curbless shower, Kohler fixtures, freestanding soaking tub.',
    createdAt: '2026-06-01T11:00:00.000Z',
  },
  {
    projectId: 'proj_oakridge_deck',
    companyId: 'company_apex_builders',
    projectName: 'Oakridge Custom Timber Deck',
    clientId: 'client_oakridge',
    clientName: 'Karen Vance',
    projectAddress: '88 Oakridge Ridge Rd, Pine Valley, OR',
    contractValue: 18000,
    approvedChangeOrders: 0,
    startDate: '2026-07-01',
    status: 'ACTIVE',
    notes: 'Two-tier composite deck with integrated low-voltage lighting and pergola.',
    createdAt: '2026-06-25T14:00:00.000Z',
  },
  {
    projectId: 'proj_metro_hvac',
    companyId: 'company_apex_builders',
    projectName: 'Metro Commercial HVAC Retrofit',
    clientId: 'client_metro',
    clientName: 'Metro Properties Inc.',
    projectAddress: '400 Industrial Parkway, Suite 200, Eugene, OR',
    contractValue: 48000,
    approvedChangeOrders: 4200,
    startDate: '2026-05-10',
    status: 'ACTIVE',
    notes: 'Ductwork replacement, 3 rooftop heat pump units, zone automation.',
    createdAt: '2026-05-01T09:00:00.000Z',
  },
  {
    projectId: 'proj_sunset_paint',
    companyId: 'company_apex_builders',
    projectName: 'Sunset Hills Exterior Painting',
    clientId: 'client_sunset',
    clientName: 'Marcus Wright',
    projectAddress: '310 Sunset Hills Court, Oak Hills, OR',
    contractValue: 12500,
    approvedChangeOrders: 800,
    startDate: '2026-07-10',
    status: 'ACTIVE',
    notes: 'Full exterior scrape, pressure wash, primer and 2-coat Duration satin finish.',
    createdAt: '2026-07-02T13:00:00.000Z',
  },
];

export const DEMO_PAYMENTS: Payment[] = [
  // Smith Kitchen: Collected $20,000 (deposit + progress 1)
  {
    paymentId: 'pay_smith_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    paymentDate: '2026-06-02',
    amount: 12000,
    paymentType: 'DEPOSIT',
    paymentMethod: 'ACH Transfer',
    referenceNumber: 'ACH-88491',
    status: 'CLEARED',
    notes: 'Initial 33% contract deposit.',
    createdBy: 'usr_sarah_admin',
    createdAt: '2026-06-02T16:00:00.000Z',
  },
  {
    paymentId: 'pay_smith_02',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    paymentDate: '2026-06-25',
    amount: 8000,
    paymentType: 'PROGRESS_PAYMENT',
    paymentMethod: 'Check',
    referenceNumber: 'CHK-4092',
    status: 'CLEARED',
    notes: 'Milestone 2 - Rough-in and framing completion.',
    createdBy: 'usr_sarah_admin',
    createdAt: '2026-06-25T17:30:00.000Z',
  },

  // Highland Bath: Collected $18,000
  {
    paymentId: 'pay_highland_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_highland_bath',
    paymentDate: '2026-06-16',
    amount: 10000,
    paymentType: 'DEPOSIT',
    paymentMethod: 'Credit Card',
    referenceNumber: 'CC-9012',
    status: 'CLEARED',
    notes: 'Deposit received.',
    createdBy: 'usr_sarah_admin',
    createdAt: '2026-06-16T12:00:00.000Z',
  },
  {
    paymentId: 'pay_highland_02',
    companyId: 'company_apex_builders',
    projectId: 'proj_highland_bath',
    paymentDate: '2026-07-12',
    amount: 8000,
    paymentType: 'PROGRESS_PAYMENT',
    paymentMethod: 'ACH Transfer',
    referenceNumber: 'ACH-99120',
    status: 'CLEARED',
    notes: 'Tile substrate and waterproofing inspection signoff.',
    createdBy: 'usr_sarah_admin',
    createdAt: '2026-07-12T14:00:00.000Z',
  },

  // Oakridge Deck: Only $4,000 collected (Material costs exceeded deposit -> Negative cash position!)
  {
    paymentId: 'pay_oakridge_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_oakridge_deck',
    paymentDate: '2026-07-02',
    amount: 4000,
    paymentType: 'DEPOSIT',
    paymentMethod: 'Check',
    referenceNumber: 'CHK-1182',
    status: 'CLEARED',
    notes: 'Initial partial deposit.',
    createdBy: 'usr_sarah_admin',
    createdAt: '2026-07-02T10:00:00.000Z',
  },

  // Metro Commercial HVAC: $15,000 collected (Large contract, high AR outstanding)
  {
    paymentId: 'pay_metro_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_metro_hvac',
    paymentDate: '2026-05-15',
    amount: 15000,
    paymentType: 'DEPOSIT',
    paymentMethod: 'Wire Transfer',
    referenceNumber: 'WIRE-33019',
    status: 'CLEARED',
    notes: 'Project commencement retainer.',
    createdBy: 'usr_sarah_admin',
    createdAt: '2026-05-15T11:00:00.000Z',
  },

  // Sunset Painting: $4,000 collected
  {
    paymentId: 'pay_sunset_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_sunset_paint',
    paymentDate: '2026-07-11',
    amount: 4000,
    paymentType: 'DEPOSIT',
    paymentMethod: 'Check',
    referenceNumber: 'CHK-7731',
    status: 'CLEARED',
    notes: 'Surface prep & materials deposit.',
    createdBy: 'usr_sarah_admin',
    createdAt: '2026-07-11T15:00:00.000Z',
  },
];

export const DEMO_PURCHASES: Purchase[] = [
  // Smith Kitchen Purchase 1: Multi-image Floor & Decor Tile Order (PUR-1001)
  {
    purchaseId: 'pur_1001',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    providerId: 'prov_floor_decor',
    providerName: 'Floor & Decor',
    purchaseDate: '2026-06-18',
    subtotal: 2635.40,
    tax: 210.85,
    totalAmount: 2846.25, // Authority transaction total
    receiptNumber: 'REC-FD-984120',
    paymentMethod: 'Visa ending 4891',
    receiptPageCount: 3,
    aiExtractedTextSummary: 'Floor & Decor purchase for Marazzi Calacatta porcelain tile, Mapei Ultracolor Plus grout in Warm Gray, tile spacers, and polymer-modified thinset mortar.',
    aiConfidence: 0.96,
    aiWarnings: [],
    analysisVersion: 'v2.4-multimodal',
    aiModel: 'gemini-3.7-flash',
    captureStatus: 'CONFIRMED',
    createdBy: 'usr_dave_field',
    createdAt: '2026-06-18T14:32:00.000Z',
    confirmedAt: '2026-06-18T14:35:00.000Z',
  },
  // Smith Kitchen Purchase 2: Single-image Home Depot rough lumber and electrical
  {
    purchaseId: 'pur_1002',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    providerId: 'prov_home_depot',
    providerName: 'Home Depot',
    purchaseDate: '2026-06-22',
    subtotal: 1320.50,
    tax: 105.64,
    totalAmount: 1426.14,
    receiptNumber: 'HD-4019-338',
    paymentMethod: 'Pro Card 0192',
    receiptPageCount: 1,
    aiExtractedTextSummary: 'Home Depot 2x4 framing lumber, Romex 12/2 electrical wire, drywall compound.',
    aiConfidence: 0.94,
    aiWarnings: [],
    captureStatus: 'CONFIRMED',
    createdBy: 'usr_mike_lead',
    createdAt: '2026-06-22T09:15:00.000Z',
    confirmedAt: '2026-06-22T09:18:00.000Z',
  },
  // Smith Kitchen Purchase 3: Ferguson luxury plumbing fixtures
  {
    purchaseId: 'pur_1003',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    providerId: 'prov_ferguson',
    providerName: 'Ferguson Bath & Kitchen',
    purchaseDate: '2026-07-05',
    subtotal: 7550.00,
    tax: 604.00,
    totalAmount: 8154.00, // Large purchase!
    receiptNumber: 'FERG-77182',
    paymentMethod: 'Commercial Account',
    receiptPageCount: 2,
    aiExtractedTextSummary: 'Kohler Artifacts pull-down bridge faucet in Vibrant Stainless, Blanco Undermount Silgranit Sink in Metallic Gray, garbage disposal.',
    aiConfidence: 0.98,
    aiWarnings: [],
    captureStatus: 'CONFIRMED',
    createdBy: 'usr_mike_lead',
    createdAt: '2026-07-05T11:20:00.000Z',
    confirmedAt: '2026-07-05T11:22:00.000Z',
  },

  // Highland Bath Purchase 1: Ferguson Kohler fixtures
  {
    purchaseId: 'pur_2001',
    companyId: 'company_apex_builders',
    projectId: 'proj_highland_bath',
    providerId: 'prov_ferguson',
    providerName: 'Ferguson Bath & Kitchen',
    purchaseDate: '2026-06-20',
    subtotal: 5200.00,
    tax: 416.00,
    totalAmount: 5616.00,
    receiptNumber: 'FERG-66291',
    paymentMethod: 'Visa ending 4891',
    receiptPageCount: 1,
    aiExtractedTextSummary: 'Kohler Purist shower valve trim, thermostatic cartridge, rain showerhead in Matte Black.',
    aiConfidence: 0.97,
    aiWarnings: [],
    captureStatus: 'CONFIRMED',
    createdBy: 'usr_dave_field',
    createdAt: '2026-06-20T10:00:00.000Z',
    confirmedAt: '2026-06-20T10:05:00.000Z',
  },

  // Oakridge Timber Deck Purchase 1: Lowe's Composite Decking & Framing (Causes negative cash position!)
  {
    purchaseId: 'pur_3001',
    companyId: 'company_apex_builders',
    projectId: 'proj_oakridge_deck',
    providerId: 'prov_lowes',
    providerName: "Lowe's",
    purchaseDate: '2026-07-04',
    subtotal: 7650.00,
    tax: 630.00,
    totalAmount: 8280.00, // Spent $8,280 vs $4,000 collected! Cash position = -$4,280
    receiptNumber: 'LOW-90123-01',
    paymentMethod: 'Pro Card 0192',
    receiptPageCount: 2,
    aiExtractedTextSummary: 'Trex Transcend Spiced Rum composite decking boards, pressure-treated 2x8 framing joists, Simpson Strong-Tie post brackets and structural screws.',
    aiConfidence: 0.95,
    aiWarnings: [],
    captureStatus: 'CONFIRMED',
    createdBy: 'usr_dave_field',
    createdAt: '2026-07-04T08:30:00.000Z',
    confirmedAt: '2026-07-04T08:35:00.000Z',
  },

  // Metro Commercial HVAC Purchase 1: Equipment & ductwork
  {
    purchaseId: 'pur_4001',
    companyId: 'company_apex_builders',
    projectId: 'proj_metro_hvac',
    providerId: 'prov_ferguson',
    providerName: 'Ferguson Bath & Kitchen',
    purchaseDate: '2026-05-28',
    subtotal: 18500.00,
    tax: 1480.00,
    totalAmount: 19980.00,
    receiptNumber: 'FERG-HVAC-1029',
    paymentMethod: 'Commercial Wire',
    receiptPageCount: 2,
    aiExtractedTextSummary: 'Rooftop heat pump condensers, motorized dampers, sheet metal duct supplies.',
    aiConfidence: 0.96,
    aiWarnings: [],
    captureStatus: 'CONFIRMED',
    createdBy: 'usr_mike_lead',
    createdAt: '2026-05-28T15:00:00.000Z',
    confirmedAt: '2026-05-28T15:05:00.000Z',
  },

  // Sunset Painting Purchase 1: Sherwin-Williams paint & supplies (High expense relative to contract value)
  {
    purchaseId: 'pur_5001',
    companyId: 'company_apex_builders',
    projectId: 'proj_sunset_paint',
    providerId: 'prov_sherwin_williams',
    providerName: 'Sherwin-Williams',
    purchaseDate: '2026-07-14',
    subtotal: 4120.00,
    tax: 329.60,
    totalAmount: 4449.60,
    receiptNumber: 'SW-88102-POR',
    paymentMethod: 'Pro Account',
    receiptPageCount: 1,
    aiExtractedTextSummary: 'Sherwin-Williams Duration Exterior Satin in Repose Gray, Loxon Concrete & Masonry Primer, Purdy brushes, 3M ScotchBlue tape.',
    aiConfidence: 0.95,
    aiWarnings: [],
    captureStatus: 'CONFIRMED',
    createdBy: 'usr_dave_field',
    createdAt: '2026-07-14T07:45:00.000Z',
    confirmedAt: '2026-07-14T07:50:00.000Z',
  },
];

export const DEMO_RECEIPT_PAGES: ReceiptPage[] = [
  // Multi-image receipt pages for Smith Kitchen Tile (PUR-1001)
  {
    receiptPageId: 'page_1001_1',
    companyId: 'company_apex_builders',
    purchaseId: 'pur_1001',
    pageNumber: 1,
    imageStoragePath: 'companies/company_apex_builders/purchases/pur_1001/receipt-images/page_001_header_tiles.jpg',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=600&q=80',
    extractedText: 'FLOOR & DECOR STORE #124\nDATE: 06/18/2026 14:15:22\nCASHIER: J. RAMIREZ\nITEM: MARAZZI CAL WHT 24X48 POL SKU: 10084920 QTY: 45 BOX @ 48.50 = 2182.50',
    aiConfidence: 0.97,
    createdAt: '2026-06-18T14:32:00.000Z',
  },
  {
    receiptPageId: 'page_1001_2',
    companyId: 'company_apex_builders',
    purchaseId: 'pur_1001',
    pageNumber: 2,
    imageStoragePath: 'companies/company_apex_builders/purchases/pur_1001/receipt-images/page_002_grout_materials.jpg',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
    extractedText: 'ITEM: MAPEI ULTRACOL PLUS WARM GRY 10LB SKU: 409912 QTY: 6 @ 24.90 = 149.40\nITEM: LATICRETE 254 PLAT THINSET 50LB SKU: 339102 QTY: 8 @ 37.95 = 303.50',
    aiConfidence: 0.95,
    createdAt: '2026-06-18T14:32:15.000Z',
  },
  {
    receiptPageId: 'page_1001_3',
    companyId: 'company_apex_builders',
    purchaseId: 'pur_1001',
    pageNumber: 3,
    imageStoragePath: 'companies/company_apex_builders/purchases/pur_1001/receipt-images/page_003_totals.jpg',
    imageUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=600&q=80',
    extractedText: 'SUBTOTAL: 2,635.40\nTAX 8.00%: 210.85\nTOTAL: $2,846.25\nVISA: ************4891\nAUTH: 094812\nTHANK YOU FOR SHOPPING AT FLOOR & DECOR',
    aiConfidence: 0.98,
    createdAt: '2026-06-18T14:32:30.000Z',
  },
];

export const DEMO_PURCHASE_ITEMS: PurchaseItem[] = [
  // Items for PUR-1001 (Multi-image Floor & Decor order)
  {
    itemId: 'item_1001_1',
    companyId: 'company_apex_builders',
    purchaseId: 'pur_1001',
    description: 'Marazzi Calacatta White Porcelain Tile',
    sku: '10084920',
    productCode: 'MAR-CAL-2448',
    brand: 'Marazzi',
    manufacturer: 'Marazzi USA',
    category: 'Tile & Stone',
    colorName: 'Calacatta White',
    colorCode: 'CAL-WHT',
    finish: 'Polished',
    size: '24" x 48"',
    dimensions: '24 in x 48 in x 9 mm',
    quantity: 45,
    unit: 'box',
    unitPrice: 48.50,
    lineTotal: 2182.50,
    rawItemText: 'MARAZZI CAL WHT 24X48 POL 10084920',
    additionalSpecifications: [
      { name: 'Tile Thickness', value: '9 mm' },
      { name: 'Shade Variation', value: 'V3 - Moderate' },
      { name: 'PEI Rating', value: 'IV - Heavy Traffic' },
      { name: 'Edge Treatment', value: 'Rectified' }
    ],
    sourcePageNumbers: [1],
    confidence: 0.98,
    createdAt: '2026-06-18T14:33:00.000Z',
  },
  {
    itemId: 'item_1001_2',
    companyId: 'company_apex_builders',
    purchaseId: 'pur_1001',
    description: 'Mapei Ultracolor Plus FA Grout',
    sku: '409912',
    modelNumber: 'MAP-ULTRA-93',
    brand: 'Mapei',
    manufacturer: 'Mapei Corp',
    category: 'Tile Setting Materials',
    colorName: 'Warm Gray (#93)',
    colorCode: '93',
    finish: 'Fine Aggregate (Non-Sanded Finish)',
    size: '10 lb Bag',
    quantity: 6,
    unit: 'bag',
    unitPrice: 24.90,
    lineTotal: 149.40,
    rawItemText: 'MAPEI ULTRACOL PLUS WARM GRY 10LB 409912',
    additionalSpecifications: [
      { name: 'Grout Color Code', value: 'Color 93 Warm Gray' },
      { name: 'Joint Width Suitability', value: '1/16 in to 3/4 in' },
      { name: 'Mold/Mildew Resistance', value: 'BioBlock Technology' }
    ],
    sourcePageNumbers: [2],
    confidence: 0.95,
    createdAt: '2026-06-18T14:33:00.000Z',
  },
  {
    itemId: 'item_1001_3',
    companyId: 'company_apex_builders',
    purchaseId: 'pur_1001',
    description: 'Laticrete 254 Platinum Polymer-Modified Mortar',
    sku: '339102',
    brand: 'Laticrete',
    category: 'Tile Adhesives',
    colorName: 'White',
    size: '50 lb Bag',
    quantity: 8,
    unit: 'bag',
    unitPrice: 37.95,
    lineTotal: 303.50,
    rawItemText: 'LATICRETE 254 PLAT THINSET 50LB WHT',
    additionalSpecifications: [
      { name: 'Polymer Formulation', value: 'High-Flexibility ANSI A118.15' },
      { name: 'Substrate Compatibility', value: 'Concrete, Cement Board, Exterior Plywood' }
    ],
    sourcePageNumbers: [2],
    confidence: 0.94,
    createdAt: '2026-06-18T14:33:00.000Z',
  },
];

export const DEMO_PROJECT_PHOTOS: ProjectPhoto[] = [
  {
    photoId: 'photo_smith_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
    caption: 'Kitchen demo complete. Rough-in plumbing and electrical ready for inspection.',
    phase: 'IN_PROGRESS',
    tags: ['Demo', 'Rough-In', 'Plumbing'],
    takenAt: '2026-06-10',
    createdAt: '2026-06-10T11:20:00.000Z',
    uploadedBy: 'Dave Miller',
  },
  {
    photoId: 'photo_smith_02',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200&q=80',
    caption: 'Custom maple shaker cabinets set and leveled. Island prep in progress.',
    phase: 'IN_PROGRESS',
    tags: ['Cabinets', 'Carpentry'],
    takenAt: '2026-06-18',
    createdAt: '2026-06-18T16:45:00.000Z',
    uploadedBy: 'Mike Rodriguez',
  },
  {
    photoId: 'photo_smith_03',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    caption: 'Initial state before demolition. Documenting existing gas and water line positions.',
    phase: 'BEFORE',
    tags: ['Site Survey', 'Before'],
    takenAt: '2026-06-01',
    createdAt: '2026-06-01T09:15:00.000Z',
    uploadedBy: 'Mike Rodriguez',
  },
  {
    photoId: 'photo_highland_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_highland_bath',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    caption: 'Calacatta polished porcelain 24x48 tile wall install in walk-in shower.',
    phase: 'IN_PROGRESS',
    tags: ['Tile', 'Shower', 'Porcelain'],
    takenAt: '2026-06-19',
    createdAt: '2026-06-19T15:00:00.000Z',
    uploadedBy: 'Sarah Chen',
  },
  {
    photoId: 'photo_highland_02',
    companyId: 'company_apex_builders',
    projectId: 'proj_highland_bath',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1200&q=80',
    caption: 'Frameless glass panel inspection and brass fixture test completed.',
    phase: 'INSPECTION',
    tags: ['Fixtures', 'Inspection'],
    takenAt: '2026-06-21',
    createdAt: '2026-06-21T10:30:00.000Z',
    uploadedBy: 'Dave Miller',
  },
  {
    photoId: 'photo_oakridge_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_oakridge_deck',
    imageUrl: 'https://images.unsplash.com/photo-1591825729269-caeb344f6df2?auto=format&fit=crop&w=1200&q=80',
    caption: 'Foundation footings and pressure-treated joist framing secured with hurricane ties.',
    phase: 'IN_PROGRESS',
    tags: ['Framing', 'Structural'],
    takenAt: '2026-06-12',
    createdAt: '2026-06-12T14:00:00.000Z',
    uploadedBy: 'Dave Miller',
  }
];

export const DEMO_PROJECT_NOTES: ProjectNote[] = [
  {
    noteId: 'note_smith_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    title: 'Color & Paint Palette Specifications',
    content: 'Client approved Sherwin-Williams palette for open concept kitchen and dining area. Low-VOC Emerald line specified throughout.',
    category: 'PAINT_COLOR',
    colorCodes: [
      { label: 'Main Kitchen Walls', code: 'SW 7005 Pure White', brand: 'Sherwin-Williams', finish: 'Emerald Matte', hexPreview: '#EDEAE0' },
      { label: 'Cabinet Perimeter', code: 'SW 7006 Extra White', brand: 'Sherwin-Williams', finish: 'Urethane Trim Enamel Satin', hexPreview: '#F2F1EC' },
      { label: 'Island Accent Base', code: 'SW 6244 Naval (Navy)', brand: 'Sherwin-Williams', finish: 'Satin', hexPreview: '#1E2B37' },
      { label: 'Ceilings & Trim', code: 'SW 7008 Alabaster', brand: 'Sherwin-Williams', finish: 'Flat / Semi-Gloss', hexPreview: '#EDEAE0' }
    ],
    isPinned: true,
    createdAt: '2026-06-03T10:00:00.000Z',
    updatedAt: '2026-06-04T11:30:00.000Z',
    createdBy: 'Sarah Chen'
  },
  {
    noteId: 'note_smith_02',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    title: 'Site Access & Lockbox Code',
    content: 'Front garage side-door keypad code: 4892#. Please ensure gate is latched due to client golden retriever. Water main shutoff located behind laundry panel.',
    category: 'ACCESS_SITE',
    isPinned: true,
    createdAt: '2026-06-01T08:00:00.000Z',
    createdBy: 'Mike Rodriguez'
  },
  {
    noteId: 'note_smith_03',
    companyId: 'company_apex_builders',
    projectId: 'proj_smith_kitchen',
    title: 'Quartz Slab & Backsplash Specs',
    content: 'Silestone Calacatta Gold 3cm polished quartz for perimeter and waterfall island. Backsplash: 3x12 Cloe White glazed ceramic tile in vertical stacked bond.',
    category: 'SPECIFICATION',
    isPinned: false,
    createdAt: '2026-06-08T13:45:00.000Z',
    createdBy: 'Sarah Chen'
  },
  {
    noteId: 'note_highland_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_highland_bath',
    title: 'Master Bath Paint & Grout Formulas',
    content: 'Benjamin Moore Aura Bath & Spa moisture-resistant finish specified for all drywall areas.',
    category: 'PAINT_COLOR',
    colorCodes: [
      { label: 'Bath Drywall', code: 'BM HC-172 Revere Pewter', brand: 'Benjamin Moore', finish: 'Aura Bath & Spa Matte', hexPreview: '#CCC7B9' },
      { label: 'Vanity Cabinetry', code: 'BM 2125-10 Black Beauty', brand: 'Benjamin Moore', finish: 'Advance Semi-Gloss', hexPreview: '#222326' },
      { label: 'Shower Tile Grout', code: 'Mapei #93 Warm Gray', brand: 'Mapei Ultracolor', finish: 'FA Non-Sanded', hexPreview: '#B3ACA3' }
    ],
    isPinned: true,
    createdAt: '2026-06-15T09:00:00.000Z',
    createdBy: 'Mike Rodriguez'
  },
  {
    noteId: 'note_oakridge_01',
    companyId: 'company_apex_builders',
    projectId: 'proj_oakridge_deck',
    title: 'Trex Composite & Stain Specifications',
    content: 'Decking: Trex Transcend Lineage in Island Mist. Railing: Signature Aluminum in Charcoal Black. Ledger board fasteners: 1/2" Simpson SDS heavy duty structural screws.',
    category: 'SPECIFICATION',
    isPinned: false,
    createdAt: '2026-06-11T16:00:00.000Z',
    createdBy: 'Dave Miller'
  }
];
